version: 0.2
phases:
  build:
    commands:
      - npm install
  post_build:
    commands:
      - zip -r $(date +%Y-%m-%d).zip *
artifacts:
  files:
    - '$(date +%Y-%m-%d).zip'
  name: app-$(date +%Y-%m-%d)
